### ISSUE TITLE
example without-a-bundler fails to build

### ISSUE THREAD

**Issue by darkoverlordofdata** [wasm-tool/wasm-pack-plugin#124]
uname -all
```
Linux penguin 5.4.151-16908-gff376e5d5ee1 #1 SMP PREEMPT Sat Dec 11 19:42:45 PST 2021 aarch64 GNU/Linux
```

I'm trying to build the example without-a-bundler and it fails:
```
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.24s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/darko/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.78/src/descriptor.rs:205:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_bounds_check
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:76:5
   3: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   4: wasm_bindgen_cli_support::descriptor::Function::decode
   5: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
   6: wasm_bindgen_cli_support::descriptors::execute
   7: wasm_bindgen_cli_support::Bindgen::generate_output
   8: wasm_bindgen_cli_support::Bindgen::generate
   9: wasm_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "/home/darko/.cache/.wasm-pack/wasm-bindgen-cargo-install-0.2.78/wasm-bindgen" "/home/darko/GitHub/wasm-bindgen/target/wasm32-unknown-unknown/release/without_a_bundler.wasm" "--out-dir" "/home/darko/GitHub/wasm-bindgen/examples/without-a-bundler/pkg" "--typescript" "--target" "web"

```

**Comment by darkoverlordofdata** [comment]
You may as well close this. I've tried other examples, and they fail also. the thread in common seems to be wasm. The eror message on some of them give the error as no binary available for platform aarch64. So I guess I wait for arm support. Too bad. I started a couple of projects on my asus and it died. I think I shoula stuck with c/c++.
